name: Release & Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Test, Bump Version & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Bump version
        id: version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # automatisch Version erhöhen (z. B. patch)
          npm version patch -m "chore(release): %s [skip ci]"
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Push version commit & tag
        run: |
          git push origin main --follow-tags

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.new_version }}"
          name: "Release v${{ env.new_version }}"
          generate_release_notes: true